import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Wiki content collection.
 *
 * Articles live at src/content/<locale>/<contentType>/<slug>.mdx
 * The `id` generated by the glob loader is the path relative to base, without extension,
 * e.g. "en/bosses/emberfang".
 *
 * Frontmatter is validated at build time by the Zod schema below. A missing or
 * malformed field fails the build immediately.
 *
 * `image` uses the `image()` helper so covers are processed by Astro Image
 * (auto WebP/AVIF + responsive srcset). Frontmatter value is a path relative
 * to the MDX file, e.g. `image: '../../../assets/covers/emberfang-cover.svg'`.
 * At build time `entry.data.image` is `ImageMetadata | undefined`. For an
 * absolute og:image URL, read `.src` and prefix with `siteUrl`.
 */
const wiki = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/wiki' }),
  schema: () =>
    z.object({
      title: z.string().max(60),
      description: z.string().min(140).max(160),
      category: z.string(),
      date: z.coerce.date(),
      lastModified: z.coerce.date().optional(),
      image: z.string().regex(/^\/images\/[\w.-]+$/),
      tags: z.array(z.string()).default([]),
      noindex: z.boolean().default(false),
      /** Quick-answer summary shown before the article body (AI Overviews / featured snippet). */
      summary: z.string().max(200).optional(),
      /** Article author name (E-E-A-T signal). Falls back to site.defaultAuthor. */
      author: z.string().optional(),
    }),
});

export const collections = { wiki };
